language: php

matrix:
  include:
    - php: 7.0
      env: TYPO3_VERSION="typo3/cms=^7.6" NIMUT_TESTING_FRAMEWORK="nimut/testing-framework"
    - php: 7.1
      env: TYPO3_VERSION="typo3/cms=^8.7" NIMUT_TESTING_FRAMEWORK="nimut/testing-framework" UPLOAD_CODE_COVERAGE=yes
    - php: 7.2
      env: TYPO3_VERSION="typo3/minimal=^9.3" NIMUT_TESTING_FRAMEWORK="nimut/testing-framework=dev-master"
    - php: 7.2
      env: TYPO3_VERSION="typo3/minimal=dev-master" NIMUT_TESTING_FRAMEWORK="nimut/testing-framework=dev-master"

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache/composer

sudo: false

addons:
  apt:
    packages:
      - parallel

before_install:
  - composer self-update
  - composer --version
  - if [ "$GITHUB_COMPOSER_AUTH" ]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi

before_script:
  # Rename our working directory, required for Extension upload to TER.
  - cd .. && mv typo3-extension-tinyurls tinyurls && cd tinyurls
  - if [ $TYPO3_VERSION = "typo3/minimal=dev-master" ]; then composer config minimum-stability dev && composer require $TYPO3_VERSION --prefer-stable --prefer-dist; fi
  - if [ $TYPO3_VERSION != "typo3/minimal=dev-master" ]; then composer require $TYPO3_VERSION; fi
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

jobs:
  include:
    - stage: test
      script: ./.travis/test_phpcs.sh
    - script: ./.travis/test_phpunit.sh
    - script: ./.travis/test_lint.sh
    - script: ./.travis/test_functional.sh
    - stage: deploy
      script: ./.travis/deploy_ter.sh
