language: php

php:
  - 7

env:
  - TYPO3_VERSION=^7.6.0
  - TYPO3_VERSION=^8.0.0
  - TYPO3_VERSION=dev-master

sudo: false
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache/composer

addons:
  apt:
    packages:
      - parallel

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version
  - if [ "$GITHUB_COMPOSER_AUTH" ]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi

before_script:
  # Rename our working directory, required for Extension upload to TER.
  - cd .. && mv typo3-extension-tinyurls tinyurls && cd tinyurls
  - composer require typo3/cms=$TYPO3_VERSION
  - export TYPO3_PATH_WEB=$PWD/.Build/Web
  - if [ -d $PWD/.Build/vendor/typo3/cms/components ]; then ln -s "$PWD/.Build/vendor/typo3/cms/components" .Build/Web/components; fi

script:
  - >
    echo;
    echo "Running phpcs";
    .Build/bin/phpcs --config-set installed_paths $PWD/.Build/vendor/de-swebhosting/php-codestyle/PhpCodeSniffer,Tests/CodeSniffer;
    .Build/bin/phpcs --standard=PSRTinyurls Classes Tests/Unit Tests/Functional ext_localconf.php
  - >
    echo;
    echo "Determining phpunit config path";
    if [ -d ".Build/vendor/typo3/cms/components/testing_framework/Resources/Core/Build" ]; then
      export PHPUNIT_CONFIG_PATH=".Build/vendor/typo3/cms/components/testing_framework/Resources/Core/Build";
    else
      export PHPUNIT_CONFIG_PATH=".Build/vendor/typo3/cms/typo3/sysext/core/Build";
    fi
  - >
    echo;
    echo "Running unit tests";
    .Build/bin/phpunit -c $PHPUNIT_CONFIG_PATH/UnitTests.xml Tests/Unit/
  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
  - >
    echo;
    export typo3DatabaseName="typo3";
    export typo3DatabaseHost="localhost";
    export typo3DatabaseUsername="root";
    export typo3DatabasePassword="";
    find . -wholename '*Tests/Functional/*Test.php' ! -path "./.Build/*" | parallel --gnu 'echo; echo "Running functional test suite {}"; .Build/bin/phpunit --colors -c $PHPUNIT_CONFIG_PATH/FunctionalTests.xml {}'

after_script:
  - >
    if [ -n "$TRAVIS_TAG" ] && [ -n "$TYPO3_ORG_USERNAME" ] && [ -n "$TYPO3_ORG_PASSWORD" ]; then
      echo -e "Preparing upload of release ${TRAVIS_TAG} to TER\n"
      curl -sSL https://raw.githubusercontent.com/alrra/travis-after-all/1.4.4/lib/travis-after-all.js | node
      if [ $? -eq 0 ]; then
        # Cleanup before we upload
        git reset --hard HEAD && git clean -fx
        TAG_MESSAGE=`git tag -n10 -l $TRAVIS_TAG | sed 's/^[0-9.]*[ ]*//g'`
        echo "Uploading release ${TRAVIS_TAG} to TER"
        .Build/bin/upload . "$TYPO3_ORG_USERNAME" "$TYPO3_ORG_PASSWORD" "$TAG_MESSAGE"
      fi;
    fi;
